stages:
  - setup
  - validate
  - build
  - release

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

.toml-attribute:
  image: python:3
  stage: setup
  variables:
    TOML_SECTION: project
  script:
    - ATTRIBUTE=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['$TOML_SECTION']['$TOML_ATTRIBUTE'])")
    - echo "$VARIABLE=$ATTRIBUTE" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

name:
  extends: .toml-attribute
  variables:
    TOML_ATTRIBUTE: name
    VARIABLE: NAME

.python-dev:
  image: python:3
  before_script:
    - pip install --upgrade pip
    - pip install .[dev]
  needs: [ ]

pylint:
  extends: .python-dev
  stage: validate
  script:
    - pylint --output-format=pylint_gitlab.GitlabCodeClimateReporter:pylint.txt roman.py test
  artifacts:
    reports:
      codequality: pylint.txt
    paths:
      - pylint.txt

pytest:
  extends: .python-dev
  stage: validate
  script:
    - pytest
  artifacts:
    reports:
      junit: pytest.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - pytest.xml
      - coverage.xml
  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

python-build:
  image: python:3
  stage: build
  script:
    - pip install --upgrade pip
    - pip install --upgrade build
    - python -m build
  artifacts:
    paths:
      - dist/*

.twine:
  image: python:3
  stage: release
  script:
    - pip install --upgrade pip
    - pip install twine
    - python -m twine upload --verbose --repository $TWINE_REPOSITORY dist/*
  needs:
    - python-build

twine-testpypi:
  extends: .twine
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $TEST_PYPI_TOKEN
    TWINE_REPOSITORY: testpypi
  only:
    - develop
  environment:
    name: TestPyPI
    url: https://test.pypi.org/project/$NAME/
  needs:
    - name
    - python-build

twine-pypi:
  extends: .twine
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_TOKEN
    TWINE_REPOSITORY: pypi
  only:
    - master
  environment:
    name: PyPI
    url: https://pypi.org/project/$NAME/
  needs:
    - name
    - python-build

twine-gitlab:
  extends: .twine
  variables:
    TWINE_USERNAME: $CI_REGISTRY_USER
    TWINE_PASSWORD: $CI_REGISTRY_PASSWORD
    TWINE_REPOSITORY: gitlab
    TWINE_REPOSITORY_URL: $CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/pypi
  only:
    - master
  environment:
    name: GitLab Package Registry
    url: "$CI_PROJECT_URL/-/packages/pypi"
  needs:
    - python-build
